# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='submission',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='file',
            name='datePosted',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(null=True, upload_to='noodle/uploads/%Y/%m/%d'),
        ),
    ]
