# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0002_auto_20170308_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='noodle.Material')),
                ('deadline', models.DateTimeField()),
                ('submissionDate', models.DateTimeField()),
            ],
        ),
    ]
