# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0003_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='couMaintainedBy',
        ),
        migrations.RemoveField(
            model_name='material',
            name='accessedBy',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staMaintainedBy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuMaintainedBy',
        ),
    ]
