# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0003_auto_20170316_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='id',
        ),
        migrations.AlterField(
            model_name='file',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='noodle.Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
