# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0004_auto_20170316_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noodle.Material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
