# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0004_auto_20170309_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ImageField(blank=True, upload_to='profile_images')),
            ],
        ),
    ]
