# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0005_auto_20170316_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
