# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-17 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0006_auto_20170316_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 3, 17, 13, 26, 10, 831000, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
