# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0007_auto_20170317_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='submission',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
