# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noodle', '0009_auto_20170320_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=1024)),
                ('slug', models.SlugField(unique=True)),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Announcement', to='noodle.Course')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='noodle/uploads/%Y/%m/%d'),
        ),
    ]
