# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('submissionDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('courseID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('couMaintainedBy', models.ManyToManyField(related_name='couMaintenanceOf', to='noodleApp.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('visibility', models.BooleanField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('staMaintainedBy', models.ManyToManyField(related_name='staMaintenanceOf', to='noodleApp.Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('yearOfStudy', models.IntegerField(default=1)),
                ('enrolledIn', models.ManyToManyField(related_name='students', to='noodleApp.Course')),
                ('stuMaintainedBy', models.ManyToManyField(related_name='stuMaintenanceOf', to='noodleApp.Admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='accessedBy',
            field=models.ManyToManyField(related_name='hasAccess', to='noodleApp.Student'),
        ),
        migrations.AddField(
            model_name='material',
            name='courseFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='noodleApp.Course'),
        ),
        migrations.AddField(
            model_name='material',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdMaterial', to='noodleApp.Staff'),
        ),
        migrations.AddField(
            model_name='file',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noodleApp.Material'),
        ),
        migrations.AddField(
            model_name='course',
            name='staffManagers',
            field=models.ManyToManyField(related_name='courses', to='noodleApp.Staff'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noodleApp.Subject'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noodleApp.Material'),
        ),
    ]
